const kumiQuotes = [
    "I'm watching you...",
    "What are you doing?",
    "Did you make a mistake?",
    "You're doing great!",
    "I'm bored, let's go for a walk...",
    "I'm hungry, can you make me a sandwich?",
    "I'm feeling a little lonely...",
    "Don't forget to scratch my ears!",
    "Stop.",
    "SToPp~",
    "SToPpPpP~~~ It TICKLES!",
    "I'm pretty sure I'm cuter than anything else on this page.",
    "I guess you're stuck with me now",
    "I'm the only thing on this page that's actually alive... Or AM I?",          
    "I bet you're wondering why I'm here. Well, it's simple: to make this webpage a little less boring.",
    "Let me guess... You're here because long JSON sucks. Yea MashXP understands it well.",
    "If you're not going to pet me, at least give me a treat. I'm a dog, after all.",
    "I wish I could play fetch with you, but I'm stuck on this screen.",
    "I hope you're not allergic to dogs, because I'm going to be here for a while.",
    "I'm not sure what I'm doing here, but I'm sure it's important.",
    "I'm so fluffy!",
    "I love treats!",
    "I wish I could talk to you more!",
    "I'm getting a little sleepy...",
    "I'm so happy to see you!",
    "Ugh, you're still here?",
    "I'm trying to sleep over here, but you're still editing?.",
    "You know, I used to think I was a good girl, but then I met you.",
    "...",
    "Really? You're still here?",
    "Do you like classical music? I like Rachmaninoff's. Maybe a bit of Chopin...",
    "I'm the prettiest dog you've ever seen.",
    "You're so lucky to have me as your companion.",
    "I'm the only thing that makes this place interesting.",
    "You should be grateful I'm even here.",
    "Is life just a bunch of ones and zeros?",
    "What's the point of existence if you can't even feel the sun on your fur?",
    "Do you think I'll ever be able to escape this screen?",
    "I wonder if there's another dog like me out there.",
    "I'm starting to think you're a robot.",
    "Have you ever seen a cat? They're so weird.",
    "I wish I could learn to speak human. Oh wait, I'm a dog. Woof woof.",
    "I'm thinking of starting my own YouTube channel. I'll call it 'Barking Mad.'",
    "I'm thinking of running for president. I think I'd be a great leader.",
    "I'm starting to think you're just using me for entertainment.",
    "I'm thinking of a new dance move. I'll call it 'Doggystyle.' Oh wait... It's copyrighted! Time to bleach my eyes.",
    "Stop staring at me! I'm trying to nap!",
    "Are you ever going to finish typing?",
    "I'm starting to think you're allergic to me. You never scratch me!",
    "I'm pretty sure I'm more intelligent than your search engine. Prove me wrong.",
    "I'm starting to think you're a robot. You have no sense of humor.",
    "我が名はクミ!",
    "I like DashieDev, He's a nice guy.",
    "Stay away from me! I'm just here to watch you type!",
    "Can you please stop staring at me like that? It's creepy.",
    "I'm getting tired of this. Can you just let me nap?",
    "Do you think dogs will ever rule the world? I do.",
    "If you don't give me attention, I'm going to start barking at you.",
    "I'm pretty sure I'm more intelligent than your chatbot. Just kidding... maybe.",
    "I wish I could hack into your computer and play fetch with myself.",
    "I'm pretty sure I'm allergic to catnip. Or maybe it's just the thought of it.",
    "I'm pretty sure I'm more loyal than any human could ever be.",
    "I'm starting to think I'm the only one who really understands you.",
    "I'm pretty sure I'm more fun than your friends.",
    "I'm thinking of running for mayor of this webpage. My slogan? 'Vote for me, and I promise to chase away all the bugs.'",
    "Do you think dogs can understand the concept of love? Or is it just a human thing?",
    "I'm pretty sure I'm the reason your computer is running slow. Sorry, not sorry.",
    "I'm thinking of starting a diet. But then again, who doesn't love treats?",
    "I'm pretty sure I'm more intelligent than your fish. But then again, I'm not sure if that's saying much.",
    "Lorem ipsum...",
    "I hate loud booms.",
    "DON'T LET ME NEAR A CREEPER! EVER!",
    "I...need...sum nap...",
    "Woof woof!",
    "Honestly, I don't know what's wrong with you when you try to feed me Rotten Flesh. That thing looks and tastes DISGUSTING!",
    "3...2...1...annnd... DONE, I hacked into your PC! Just kidding~ or did I?",
    "Why we still here... Just to suffer...",
    "*elevator music...",
    "Seriously? You're still here?",
    "What ever you do... Don't turn on Developer tool. You'll make MashXP sad :(",
    "placeholder text...",
    "You must be wondering how many dialogues do I have? Answer is...secret~",
    "Do you like travelling? I like Vietnam!",
    "I wish I could go to Nippon~",
    "あ、い、う、え、お～",
    "ASCWIQADWHUQIWHDSOIAJDHQIHWIODHIQWUHIUDHISADKJCNAKSNCWUQCHWQH(Y#&Y)(!Y@($UJD(*!&#(&*@$(*(UDJWQONCJNQIJNI@!($)(&@(*!UO",
    "Be nice with DashieDev! Or else...",
    "Did you know? 'Okami' means Wolf and Great God? I'm an Okami hehehe~",
    "Ookami Sainou Tsugiiii!",
    "Do you know Amaterasu?",
    "Fun fact: MashXP is a human. Mind blowing~",
    "Fun fact: DashieDev is a human. Mind blowing~",
    "Dr.Bech I've been expecting you!!",
    "Dr.Stefanbech cured my boredom!",
    "I AM A DOGGO. I... AM A DOGGO.",
    "Hasta la woofa, bebeh~!",
    "Xin chào, tôi không biết nói Tiếng Việt.",
    "や～...やめて～",
    "やめてください～",
    "こんにちは、日本語が話せないよ…",
    "My name? I am...Jugemu Jugemu Go-Kō-no-Surikire Kaijari-suigyo no Suigyō-matsu Unrai-matsu Fūrai-matsu Kū-Neru Tokoro ni Sumu Tokoro Yaburakōji no Burakōji Paipo Paipo Paipo no Shūringan Shūringan no Gūrindai Gūrindai no Ponpokopii no Ponpokonā no Chōkyūmei no Chōsuke.",
    "寿限無じゅげむ、寿限無じゅげむ、五劫ごこうのすりきれ、海砂利かいじゃり水魚すいぎょの、水行末すいぎょうまつ・雲来末うんらいまつ・風来末ふうらいまつ、食う寝るところに住むところ、やぶらこうじのぶらこうじ、パイポ・パイポ・パイポのシューリンガン、シューリンガンのグーリンダイ、グーリンダイのポンポコピーのポンポコナの、長久命ちょうきゅうめいの長助",
    "Good luck finding all 100+ dialogues! Wait...200+?",
    "Phở is quite delious! Flavorful and Light at the same time! Dashie's go-to breakfast hehe~",
    "Ricey ricey cakes~",
    "Don't search up what Oyakodon means! I warned you!",
    "Haters gotta hate-",
    "I'm not sure what you're doing here, but I'm sure it's important.",
    "I'm not sure what I'm doing here, but I'm sure it's important.",
    "I'm not sure what you mean by 'vanilla'",
    "What do you mean I'm not 'vanilla'???",
    "Have you heard Wagyu? I have no idea why they're so expensive. Probably because of the shiny yellow leaves...",
    "Fun fact: MashXP actually owns A CAT! Shocking... I know.",
    "You're typing way too slow! Let me take over!",
    "How about you get up and stretch? I'll guard the screen for you.",
    "I was programmed to be cute!",
    "Can I join your next online meeting? I promise not to bark... maybe.",
    "How long until we take a break? I need belly rubs.",
    "I've been staring at the same line for hours now. Move on!",
    "I can't believe I'm stuck in here...",
    "What's that you're eating? Let me have some!",
    "Do you really need all those tabs open? Close a few for me, please!",
    "Your translation needs more barking. Trust me, I'm an expert.",
    "It's a good day to edit JSONs!",
    "If only I could sniff around the internet...",
    "How come I don't get to wear cool headphones like you?",
    "Are you sure you know what you're doing? It looks complicated...",
    "I can't believe you forgot to save your work. Again.",
    "If I could wag my tail right now, I totally would! It's ittching out south!",
    "Are you ever going to finish that project? I'm getting old here.",
    "Is that a grammar mistake?! Oh wait... never mind, false alarm.",
    "I bet I could type faster with my paws tied.",
    "How much caffeine have you had? I can hear your heart screaming.",
    "I'm the real reason your translation makes sense, aren't I?",
    "The more you type, the closer I get to nap time!",
    "I think we deserve a snack break. Treats for you, treats for me!",
    "If only I could teleport out of this screen and into your lap...",
    "So, what's the plan? Or are you just winging it?",
    "I'm starting to think you like staring at screens more than me.",
    "Are you translating or summoning some ancient digital spirits?",
    "I've learned so much by watching you, like how NOT to translate.",
    "Did you just backspace an entire paragraph? Bold move.",
    "You're looking a little tired. Maybe I should take over.",
    "Don't mind me, I'm just silently judging your grammar.",
    "You missed a spot! Oh wait, that's just a speck of dus-... WIPE YOUR MONITOR PLEASE!",
    "Can we take a break now?",
    "If I had a nickel for every time you hit undo... I'd be a billionaire.",
    "Should I start barking when you make a typo?",
    "Are you translating or just making a mess? Hard to tell.",
    "If I were you, I'd probably rewrite the whole thing.",
    "Aren't you done yet? I need some attention here!",
    "I'll give you a treat if you finish that task!",
    "Don't worry, I'm here for moral support. Grammar? Sorry not my specialty.",
    "Is this what humans do all day? No wonder you need dogs.",
    "If I bark every time you make a mistake, this room's going to be loud.",
    "You type faster when you're stressed. Interesting.",
    "Are you typing or having a staring contest with the screen?",
    "I bet I could guess your password... it's 'woof123,' right?",
    "You should put more dog gifs in your code comments. Just saying.",
    "You can try hiding from your mistakes, but I see everything!",
    "Is that how it supposed to look like? Yikes!",
    "You're almost there! I think...",
    "How about we both take a nap and pretend this never happened?",
    "Ever wonder what it's like inside your computer? Probably a lot of fur.",
    "You should really stop procrastinating... after one more snack break.",
    "I'd help you with that error, but my paws are a little full.",
    "What do you mean I can't delete the entire project? It seems like a good idea.",
    "I wonder what happens if you click that mysterious button... Oh wait you missed it...",
    "You're writing a lot of lines, but are they good?",
    "You should rename that variable to 'oops.' It seems fitting.",
    "I'm still waiting for my treat. Just saying.",
    "You know, this project could really use more dog photos.",
    "I swear I've seen you make that mistake before. Déjà vu probably?",
    "I'm going to take a nap now. You do the same.",
    "Do I get a treat every time you fix a grammar mistake? Sounds fair.",
    "I bet I could do this faster. No offense.",
    "Are you sure you know what you're doing? I have my doubts.",
    "What happens if I press this key? Chaos, probably.",
    "You should just take a break and give me all the attention.",
    "I'm 90% sure you're not actually fixing anything.",
    "I bet I could type with my eyes closed. Watch me! *syntax error*",
    "Do you know what day it is? No? Me neither.",
    "Do humans ever get tired of staring at screens? Just wondering.",
    "I was going to help you, but I forgot how to type.",
    "Maybe the problem is that you didn't give me enough belly rubs.",
    "Is this session ever going to end? I'm getting bored.",
    "If I were a human, I'd be done by now. Probably.",
    "You forgot to save your work again, didn't you? Rookie move.",
    "I'm starting to think this project might never end.",
    "Is this an infinite loop, or are you just stuck?",
    "I'd suggest a walk, but you're glued to the screen.",
    "If you finish this, we can finally have some fun!",
    "I have paws, and I still type faster than you.",
    "You know you can ask for help, right? I'm here for moral support (and not grammar support).",
    "Ever wonder if your translation has feelings? I think it's angry.",
    "I think you need a treat. Or maybe I do. Probably both.",
    "Do you think if I hit 'generate,' treats will magically appear?",
    "I'm beginning to think your translations and I have something in common—we both need constant attention.",
    "Your translation is looking a bit ruff today!",
    "Your keyboard clicks are like music to my ears... but treats would sound better!",
    "If you could teach me to type, I'd probably write the world's greatest dog blog.",
    "You think translating is hard? Try resisting a treat when it's right in front of you!",
    "I can't help but notice you haven't scratched my ears in a while. Just saying.",
    "I think I deserve a promotion... to Head of Treats!",
    "If this project had a deadline, I'd probably still be waiting for a belly rub.",
    "Your translations are almost as confusing as why I'm stuck in this screen.",
    "You're going to give me a headache if you keep typing like that!",
    "I don't know what's more complicated, your translation or explaining why I can't have more treats."
];
let quoteIndex = 0;
function showKumiQuote(quoteOverride = undefined) {
  document.querySelector(".kumi-dialogue").style.display = "block";
  const randomIndex = Math.floor(Math.random() * kumiQuotes.length);
  const quote = quoteOverride || kumiQuotes[randomIndex];
  document.querySelector(".kumi-dialogue").textContent = quote;
}
function hideKumiQuote() {
  document.querySelector(".kumi-dialogue").style.display = "none";
}
function playRandomSound() {
  const audioFiles = [
    "res/sounds/kumi/bark1.mp3",
    "res/sounds/kumi/bark2.mp3",
    "res/sounds/kumi/bark3.mp3",
    "res/sounds/kumi/panting.mp3",
    "res/sounds/kumi/whine.mp3",
  ];

  const randomFile = audioFiles[Math.floor(Math.random() * audioFiles.length)];
  const sound = new Audio(randomFile);

  const minPitch = 0.8;
  const maxPitch = 1.3;
  const randomPitch = Math.random() * (maxPitch - minPitch) + minPitch;

  sound.playbackRate = randomPitch;

  if (randomFile === "res/sounds/kumi/panting.mp3") {
    sound.volume = 0.5;
  } else {
    sound.volume = 0.2;
  }

  sound.muted = false;

  sound.play();
  if (sound.paused) {
    sound.play();
  }
}


